export enum Authorities {

    AUTHENTICATED = 'AUTHENTICATED',

    ACCESS_APPLICATION = 'ACCESS_APPLICATION',

    PARENT = 'PARENT',

    TRAINER = 'TRAINER',

    ADMINISTRATIVE = 'ADMINISTRATIVE'

}
