/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * Child attendance
 * @export
 * @interface Attendance
 */
export interface Attendance {
    /**
     * A date without a time-zone in the ISO-8601 calendar system.

     * @type {string}
     * @memberof Attendance
     */
    date: string;
    /**
     * Time
     * @type {string}
     * @memberof Attendance
     */
    time: string;
}

export function AttendanceFromJSON(json: any): Attendance {
    return AttendanceFromJSONTyped(json, false);
}

export function AttendanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attendance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': json['date'],
        'time': json['time'],
    };
}

export function AttendanceToJSON(value?: Attendance | null): any {
    return AttendanceToJSONTyped(value, false);
}

export function AttendanceToJSONTyped(value?: Attendance | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'time': value.time,
    };
}

