/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * 
 * @export
 * @interface AuthenticationErrorAllOf
 */
export interface AuthenticationErrorAllOf {
    /**
     * Error reason
     * @type {string}
     * @memberof AuthenticationErrorAllOf
     */
    reason: AuthenticationErrorAllOfReason;
}


/**
 * @export
 */
export const AuthenticationErrorAllOfReason = {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
    INSUFFICIENT_PRIVILEGES: 'INSUFFICIENT_PRIVILEGES'
} as const;
export type AuthenticationErrorAllOfReason = typeof AuthenticationErrorAllOfReason[keyof typeof AuthenticationErrorAllOfReason];


export function AuthenticationErrorAllOfFromJSON(json: any): AuthenticationErrorAllOf {
    return AuthenticationErrorAllOfFromJSONTyped(json, false);
}

export function AuthenticationErrorAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationErrorAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reason': json['reason'],
    };
}

export function AuthenticationErrorAllOfToJSON(value?: AuthenticationErrorAllOf | null): any {
    return AuthenticationErrorAllOfToJSONTyped(value, false);
}

export function AuthenticationErrorAllOfToJSONTyped(value?: AuthenticationErrorAllOf | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reason': value.reason,
    };
}

