/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * Credentials for authentication
 * @export
 * @interface AuthChangePassword
 */
export interface AuthChangePassword {
    /**
     * 
     * @type {string}
     * @memberof AuthChangePassword
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthChangePassword
     */
    oldPassword: string;
    /**
     * 
     * @type {string}
     * @memberof AuthChangePassword
     */
    newPassword: string;
}

export function AuthChangePasswordFromJSON(json: any): AuthChangePassword {
    return AuthChangePasswordFromJSONTyped(json, false);
}

export function AuthChangePasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthChangePassword {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'oldPassword': json['oldPassword'],
        'newPassword': json['newPassword'],
    };
}

export function AuthChangePasswordToJSON(value?: AuthChangePassword | null): any {
    return AuthChangePasswordToJSONTyped(value, false);
}

export function AuthChangePasswordToJSONTyped(value?: AuthChangePassword | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'oldPassword': value.oldPassword,
        'newPassword': value.newPassword,
    };
}

