/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * Credentials for authentication
 * @export
 * @interface AuthCredentials
 */
export interface AuthCredentials {
    /**
     * 
     * @type {string}
     * @memberof AuthCredentials
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthCredentials
     */
    password: string;
}

export function AuthCredentialsFromJSON(json: any): AuthCredentials {
    return AuthCredentialsFromJSONTyped(json, false);
}

export function AuthCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCredentials {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function AuthCredentialsToJSON(value?: AuthCredentials | null): any {
    return AuthCredentialsToJSONTyped(value, false);
}

export function AuthCredentialsToJSONTyped(value?: AuthCredentials | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

