/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BaseErrorType = {
    AUTHENTICATION: 'AUTHENTICATION',
    UNIQUENESS_VIOLATION: 'UNIQUENESS_VIOLATION',
    REFERENCE_VIOLATION: 'REFERENCE_VIOLATION',
    DATA_VALIDATION: 'DATA_VALIDATION',
    OBJECT_NOT_FOUND: 'OBJECT_NOT_FOUND',
    CLIENT_VERSION_REJECTED: 'CLIENT_VERSION_REJECTED',
    INTEGRATION: 'INTEGRATION',
    INTERNAL: 'INTERNAL'
} as const;
export type BaseErrorType = typeof BaseErrorType[keyof typeof BaseErrorType];


export function BaseErrorTypeFromJSON(json: any): BaseErrorType {
    return BaseErrorTypeFromJSONTyped(json, false);
}

export function BaseErrorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseErrorType {
    return json as BaseErrorType;
}

export function BaseErrorTypeToJSON(value?: BaseErrorType | null): any {
    return value as any;
}

