/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * Branch office address
 * @export
 * @interface BranchOfficeAddress
 */
export interface BranchOfficeAddress {
    /**
     * 
     * @type {string}
     * @memberof BranchOfficeAddress
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof BranchOfficeAddress
     */
    street: string;
    /**
     * 
     * @type {number}
     * @memberof BranchOfficeAddress
     */
    buildingNumber: number;
}

export function BranchOfficeAddressFromJSON(json: any): BranchOfficeAddress {
    return BranchOfficeAddressFromJSONTyped(json, false);
}

export function BranchOfficeAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchOfficeAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'city': json['city'],
        'street': json['street'],
        'buildingNumber': json['buildingNumber'],
    };
}

export function BranchOfficeAddressToJSON(value?: BranchOfficeAddress | null): any {
    return BranchOfficeAddressToJSONTyped(value, false);
}

export function BranchOfficeAddressToJSONTyped(value?: BranchOfficeAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'city': value.city,
        'street': value.street,
        'buildingNumber': value.buildingNumber,
    };
}

