/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * Branch office list item
 * @export
 * @interface BranchOfficeListItem
 */
export interface BranchOfficeListItem {
    /**
     * 
     * @type {string}
     * @memberof BranchOfficeListItem
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof BranchOfficeListItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BranchOfficeListItem
     */
    address: string;
}

export function BranchOfficeListItemFromJSON(json: any): BranchOfficeListItem {
    return BranchOfficeListItemFromJSONTyped(json, false);
}

export function BranchOfficeListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchOfficeListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': json['address'],
    };
}

export function BranchOfficeListItemToJSON(value?: BranchOfficeListItem | null): any {
    return BranchOfficeListItemToJSONTyped(value, false);
}

export function BranchOfficeListItemToJSONTyped(value?: BranchOfficeListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'address': value.address,
    };
}

