/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * Child
 * @export
 * @interface ChildProfile
 */
export interface ChildProfile {
    /**
     * 
     * @type {string}
     * @memberof ChildProfile
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof ChildProfile
     */
    fullName: string;
    /**
     * A date without a time-zone in the ISO-8601 calendar system.

     * @type {string}
     * @memberof ChildProfile
     */
    birthdate?: string;
    /**
     * 
     * @type {string}
     * @memberof ChildProfile
     */
    diagnosis: string;
    /**
     * 
     * @type {number}
     * @memberof ChildProfile
     */
    tuitionBalance: number;
    /**
     * 
     * @type {number}
     * @memberof ChildProfile
     */
    numberClassesPerMonth: number;
    /**
     * 
     * @type {string}
     * @memberof ChildProfile
     */
    notes?: string;
}

export function ChildProfileFromJSON(json: any): ChildProfile {
    return ChildProfileFromJSONTyped(json, false);
}

export function ChildProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fullName': json['fullName'],
        'birthdate': !exists(json, 'birthdate') ? undefined : json['birthdate'],
        'diagnosis': json['diagnosis'],
        'tuitionBalance': json['tuitionBalance'],
        'numberClassesPerMonth': json['numberClassesPerMonth'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function ChildProfileToJSON(value?: ChildProfile | null): any {
    return ChildProfileToJSONTyped(value, false);
}

export function ChildProfileToJSONTyped(value?: ChildProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullName': value.fullName,
        'birthdate': value.birthdate,
        'diagnosis': value.diagnosis,
        'tuitionBalance': value.tuitionBalance,
        'numberClassesPerMonth': value.numberClassesPerMonth,
        'notes': value.notes,
    };
}

