/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * Child attendance
 * @export
 * @interface ChildInfo
 */
export interface ChildInfo {
    /**
     * ID
     * @type {string}
     * @memberof ChildInfo
     */
    id: string;
    /**
     * fullName
     * @type {string}
     * @memberof ChildInfo
     */
    fullName: string;
}

export function ChildInfoFromJSON(json: any): ChildInfo {
    return ChildInfoFromJSONTyped(json, false);
}

export function ChildInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fullName': json['fullName'],
    };
}

export function ChildInfoToJSON(value?: ChildInfo | null): any {
    return ChildInfoToJSONTyped(value, false);
}

export function ChildInfoToJSONTyped(value?: ChildInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'fullName': value.fullName,
    };
}

