/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DayOfWeek,
    DayOfWeekFromJSON,
    DayOfWeekFromJSONTyped,
    DayOfWeekToJSON,
    UserAccountItem,
    UserAccountItemFromJSON,
    UserAccountItemFromJSONTyped,
    UserAccountItemToJSON,
} from './';


/**
 * Class schedule
 * @export
 * @interface ClassSchedule
 */
export interface ClassSchedule {
    /**
     * 
     * @type {string}
     * @memberof ClassSchedule
     */
    readonly id?: string;
    /**
     * 
     * @type {DayOfWeek}
     * @memberof ClassSchedule
     */
    day: DayOfWeek;
    /**
     * Time
     * @type {string}
     * @memberof ClassSchedule
     */
    time: string;
    /**
     * 
     * @type {UserAccountItem}
     * @memberof ClassSchedule
     */
    trainer: UserAccountItem;
}

export function ClassScheduleFromJSON(json: any): ClassSchedule {
    return ClassScheduleFromJSONTyped(json, false);
}

export function ClassScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassSchedule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'day': DayOfWeekFromJSON(json['day']),
        'time': json['time'],
        'trainer': UserAccountItemFromJSON(json['trainer']),
    };
}

export function ClassScheduleToJSON(value?: ClassSchedule | null): any {
    return ClassScheduleToJSONTyped(value, false);
}

export function ClassScheduleToJSONTyped(value?: ClassSchedule | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'day': DayOfWeekToJSON(value.day),
        'time': value.time,
        'trainer': UserAccountItemToJSON(value.trainer),
    };
}

