/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DataValidationErrorItem,
    DataValidationErrorItemFromJSON,
    DataValidationErrorItemFromJSONTyped,
    DataValidationErrorItemToJSON,
} from './';


/**
 * 
 * @export
 * @interface DataValidationErrorAllOf
 */
export interface DataValidationErrorAllOf {
    /**
     * 
     * @type {Array<DataValidationErrorItem>}
     * @memberof DataValidationErrorAllOf
     */
    details?: Array<DataValidationErrorItem>;
}

export function DataValidationErrorAllOfFromJSON(json: any): DataValidationErrorAllOf {
    return DataValidationErrorAllOfFromJSONTyped(json, false);
}

export function DataValidationErrorAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataValidationErrorAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'details': !exists(json, 'details') ? undefined : ((json['details'] as Array<any>).map(DataValidationErrorItemFromJSON)),
    };
}

export function DataValidationErrorAllOfToJSON(value?: DataValidationErrorAllOf | null): any {
    return DataValidationErrorAllOfToJSONTyped(value, false);
}

export function DataValidationErrorAllOfToJSONTyped(value?: DataValidationErrorAllOf | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'details': value.details === undefined ? undefined : ((value.details as Array<any>).map(DataValidationErrorItemToJSON)),
    };
}

