/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * 
 * @export
 * @interface DataValidationErrorItem
 */
export interface DataValidationErrorItem {
    /**
     * 
     * @type {string}
     * @memberof DataValidationErrorItem
     */
    sheet?: string;
    /**
     * 
     * @type {string}
     * @memberof DataValidationErrorItem
     */
    cell?: string;
    /**
     * 
     * @type {string}
     * @memberof DataValidationErrorItem
     */
    message?: string;
}

export function DataValidationErrorItemFromJSON(json: any): DataValidationErrorItem {
    return DataValidationErrorItemFromJSONTyped(json, false);
}

export function DataValidationErrorItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataValidationErrorItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sheet': !exists(json, 'sheet') ? undefined : json['sheet'],
        'cell': !exists(json, 'cell') ? undefined : json['cell'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function DataValidationErrorItemToJSON(value?: DataValidationErrorItem | null): any {
    return DataValidationErrorItemToJSONTyped(value, false);
}

export function DataValidationErrorItemToJSONTyped(value?: DataValidationErrorItem | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sheet': value.sheet,
        'cell': value.cell,
        'message': value.message,
    };
}

