/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseError,
    BaseErrorFromJSON,
    BaseErrorFromJSONTyped,
    BaseErrorToJSON,
    BaseErrorType,
    BaseErrorTypeFromJSON,
    BaseErrorTypeFromJSONTyped,
    BaseErrorTypeToJSON,
} from './';
import { BaseErrorToJSONTyped } from './';

/**
 * 
 * @export
 * @interface InternalError
 */
export interface InternalError extends BaseError {
}

export function InternalErrorFromJSON(json: any): InternalError {
    return InternalErrorFromJSONTyped(json, false);
}

export function InternalErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalError {
    return json;
}

export function InternalErrorToJSON(value?: InternalError | null): any {
    return InternalErrorToJSONTyped(value, false);
}

export function InternalErrorToJSONTyped(value?: InternalError | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

