/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseError,
    BaseErrorFromJSON,
    BaseErrorFromJSONTyped,
    BaseErrorToJSON,
    BaseErrorType,
    BaseErrorTypeFromJSON,
    BaseErrorTypeFromJSONTyped,
    BaseErrorTypeToJSON,
} from './';
import { BaseErrorToJSONTyped } from './';

/**
 * 
 * @export
 * @interface IntegrationError
 */
export interface IntegrationError extends BaseError {
}

export function IntegrationErrorFromJSON(json: any): IntegrationError {
    return IntegrationErrorFromJSONTyped(json, false);
}

export function IntegrationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationError {
    return json;
}

export function IntegrationErrorToJSON(value?: IntegrationError | null): any {
    return IntegrationErrorToJSONTyped(value, false);
}

export function IntegrationErrorToJSONTyped(value?: IntegrationError | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

