/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseError,
    BaseErrorFromJSON,
    BaseErrorFromJSONTyped,
    BaseErrorToJSON,
    BaseErrorType,
    BaseErrorTypeFromJSON,
    BaseErrorTypeFromJSONTyped,
    BaseErrorTypeToJSON,
} from './';
import { BaseErrorToJSONTyped } from './';

/**
 * 
 * @export
 * @interface ObjectNotFoundError
 */
export interface ObjectNotFoundError extends BaseError {
}

export function ObjectNotFoundErrorFromJSON(json: any): ObjectNotFoundError {
    return ObjectNotFoundErrorFromJSONTyped(json, false);
}

export function ObjectNotFoundErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectNotFoundError {
    return json;
}

export function ObjectNotFoundErrorToJSON(value?: ObjectNotFoundError | null): any {
    return ObjectNotFoundErrorToJSONTyped(value, false);
}

export function ObjectNotFoundErrorToJSONTyped(value?: ObjectNotFoundError | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

