/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PriceItemType,
    PriceItemTypeFromJSON,
    PriceItemTypeFromJSONTyped,
    PriceItemTypeToJSON,
} from './';


/**
 * Price item
 * @export
 * @interface PriceItem
 */
export interface PriceItem {
    /**
     * 
     * @type {PriceItemType}
     * @memberof PriceItem
     */
    type: PriceItemType;
    /**
     * Normal price
     * @type {number}
     * @memberof PriceItem
     */
    normalPrice: number;
    /**
     * Benefits price
     * @type {number}
     * @memberof PriceItem
     */
    benefitsPrice: number;
}

export function PriceItemFromJSON(json: any): PriceItem {
    return PriceItemFromJSONTyped(json, false);
}

export function PriceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': PriceItemTypeFromJSON(json['type']),
        'normalPrice': json['normalPrice'],
        'benefitsPrice': json['benefitsPrice'],
    };
}

export function PriceItemToJSON(value?: PriceItem | null): any {
    return PriceItemToJSONTyped(value, false);
}

export function PriceItemToJSONTyped(value?: PriceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': PriceItemTypeToJSON(value.type),
        'normalPrice': value.normalPrice,
        'benefitsPrice': value.benefitsPrice,
    };
}

