/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Price item type
 * @export
 */
export const PriceItemType = {
    ONE_LESSON: 'ONE_LESSON',
    TWO_LESSONS: 'TWO_LESSONS',
    THREE_LESSONS: 'THREE_LESSONS',
    FOUR_LESSONS: 'FOUR_LESSONS',
    FIVE_LESSONS: 'FIVE_LESSONS',
    SIX_LESSONS: 'SIX_LESSONS',
    SEVEN_LESSONS: 'SEVEN_LESSONS',
    EIGHT_LESSONS: 'EIGHT_LESSONS',
    NINE_LESSONS: 'NINE_LESSONS',
    TEN_LESSONS: 'TEN_LESSONS',
    ELEVEN_LESSONS: 'ELEVEN_LESSONS',
    TWELVE_LESSONS: 'TWELVE_LESSONS',
    UNLIM: 'UNLIM'
} as const;
export type PriceItemType = typeof PriceItemType[keyof typeof PriceItemType];


export function PriceItemTypeFromJSON(json: any): PriceItemType {
    return PriceItemTypeFromJSONTyped(json, false);
}

export function PriceItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceItemType {
    return json as PriceItemType;
}

export function PriceItemTypeToJSON(value?: PriceItemType | null): any {
    return value as any;
}

