/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BaseError,
    BaseErrorFromJSON,
    BaseErrorFromJSONTyped,
    BaseErrorToJSON,
    BaseErrorType,
    BaseErrorTypeFromJSON,
    BaseErrorTypeFromJSONTyped,
    BaseErrorTypeToJSON,
} from './';
import { BaseErrorToJSONTyped } from './';

/**
 * 
 * @export
 * @interface ReferenceViolationError
 */
export interface ReferenceViolationError extends BaseError {
}

export function ReferenceViolationErrorFromJSON(json: any): ReferenceViolationError {
    return ReferenceViolationErrorFromJSONTyped(json, false);
}

export function ReferenceViolationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceViolationError {
    return json;
}

export function ReferenceViolationErrorToJSON(value?: ReferenceViolationError | null): any {
    return ReferenceViolationErrorToJSONTyped(value, false);
}

export function ReferenceViolationErrorToJSONTyped(value?: ReferenceViolationError | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

