/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaskStatus,
    TaskStatusFromJSON,
    TaskStatusFromJSONTyped,
    TaskStatusToJSON,
    UserAccountItem,
    UserAccountItemFromJSON,
    UserAccountItemFromJSONTyped,
    UserAccountItemToJSON,
} from './';


/**
 * Task
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * ID
     * @type {string}
     * @memberof Task
     */
    readonly id: string;
    /**
     * Name
     * @type {string}
     * @memberof Task
     */
    name: string;
    /**
     * Description
     * @type {string}
     * @memberof Task
     */
    description: string;
    /**
     * 
     * @type {UserAccountItem}
     * @memberof Task
     */
    assignee: UserAccountItem;
    /**
     * 
     * @type {UserAccountItem}
     * @memberof Task
     */
    reporter: UserAccountItem;
    /**
     * 
     * @type {TaskStatus}
     * @memberof Task
     */
    status: TaskStatus;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'assignee': UserAccountItemFromJSON(json['assignee']),
        'reporter': UserAccountItemFromJSON(json['reporter']),
        'status': TaskStatusFromJSON(json['status']),
    };
}

export function TaskToJSON(value?: Task | null): any {
    return TaskToJSONTyped(value, false);
}

export function TaskToJSONTyped(value?: Task | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'assignee': UserAccountItemToJSON(value.assignee),
        'reporter': UserAccountItemToJSON(value.reporter),
        'status': TaskStatusToJSON(value.status),
    };
}

