/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BranchOfficeItem,
    BranchOfficeItemFromJSON,
    BranchOfficeItemFromJSONTyped,
    BranchOfficeItemToJSON,
} from './';


/**
 * Telegram bot application
 * @export
 * @interface TelegramBotApplication
 */
export interface TelegramBotApplication {
    /**
     * ID
     * @type {string}
     * @memberof TelegramBotApplication
     */
    readonly id: string;
    /**
     * Telegram username
     * @type {string}
     * @memberof TelegramBotApplication
     */
    telegramUsername: string;
    /**
     * 
     * @type {Date}
     * @memberof TelegramBotApplication
     */
    readonly createTimestamp: Date;
    /**
     * 
     * @type {BranchOfficeItem}
     * @memberof TelegramBotApplication
     */
    branchOffice?: BranchOfficeItem;
    /**
     * Phone
     * @type {string}
     * @memberof TelegramBotApplication
     */
    phone?: string;
}

export function TelegramBotApplicationFromJSON(json: any): TelegramBotApplication {
    return TelegramBotApplicationFromJSONTyped(json, false);
}

export function TelegramBotApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelegramBotApplication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'telegramUsername': json['telegramUsername'],
        'createTimestamp': (new Date(json['createTimestamp'])),
        'branchOffice': !exists(json, 'branchOffice') ? undefined : BranchOfficeItemFromJSON(json['branchOffice']),
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
    };
}

export function TelegramBotApplicationToJSON(value?: TelegramBotApplication | null): any {
    return TelegramBotApplicationToJSONTyped(value, false);
}

export function TelegramBotApplicationToJSONTyped(value?: TelegramBotApplication | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'telegramUsername': value.telegramUsername,
        'branchOffice': BranchOfficeItemToJSON(value.branchOffice),
        'phone': value.phone,
    };
}

