/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserRole,
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
} from './';


/**
 * User account
 * @export
 * @interface UserAccountListItem
 */
export interface UserAccountListItem {
    /**
     * 
     * @type {string}
     * @memberof UserAccountListItem
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof UserAccountListItem
     */
    username?: string;
    /**
     * 
     * @type {UserRole}
     * @memberof UserAccountListItem
     */
    role: UserRole;
    /**
     * 
     * @type {string}
     * @memberof UserAccountListItem
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserAccountListItem
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof UserAccountListItem
     */
    fullName: string;
}

export function UserAccountListItemFromJSON(json: any): UserAccountListItem {
    return UserAccountListItemFromJSONTyped(json, false);
}

export function UserAccountListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccountListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'role': UserRoleFromJSON(json['role']),
        'email': json['email'],
        'phone': json['phone'],
        'fullName': json['fullName'],
    };
}

export function UserAccountListItemToJSON(value?: UserAccountListItem | null): any {
    return UserAccountListItemToJSONTyped(value, false);
}

export function UserAccountListItemToJSONTyped(value?: UserAccountListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'role': UserRoleToJSON(value.role),
        'email': value.email,
        'phone': value.phone,
        'fullName': value.fullName,
    };
}

