/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserRole,
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
} from './';


/**
 * 
 * @export
 * @interface UserAccountCriteria
 */
export interface UserAccountCriteria {
    /**
     * 
     * @type {string}
     * @memberof UserAccountCriteria
     */
    lastName?: string;
    /**
     * 
     * @type {UserRole}
     * @memberof UserAccountCriteria
     */
    role?: UserRole;
    /**
     * 
     * @type {boolean}
     * @memberof UserAccountCriteria
     */
    payAttention?: boolean;
}

export function UserAccountCriteriaFromJSON(json: any): UserAccountCriteria {
    return UserAccountCriteriaFromJSONTyped(json, false);
}

export function UserAccountCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccountCriteria {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'role': !exists(json, 'role') ? undefined : UserRoleFromJSON(json['role']),
        'payAttention': !exists(json, 'payAttention') ? undefined : json['payAttention'],
    };
}

export function UserAccountCriteriaToJSON(value?: UserAccountCriteria | null): any {
    return UserAccountCriteriaToJSONTyped(value, false);
}

export function UserAccountCriteriaToJSONTyped(value?: UserAccountCriteria | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastName': value.lastName,
        'role': UserRoleToJSON(value.role),
        'payAttention': value.payAttention,
    };
}

