/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * User account item
 * @export
 * @interface UserAccountItem
 */
export interface UserAccountItem {
    /**
     * 
     * @type {string}
     * @memberof UserAccountItem
     */
    readonly id: string;
    /**
     * 
     * @type {string}
     * @memberof UserAccountItem
     */
    readonly fullName: string;
}

export function UserAccountItemFromJSON(json: any): UserAccountItem {
    return UserAccountItemFromJSONTyped(json, false);
}

export function UserAccountItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccountItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fullName': json['fullName'],
    };
}

export function UserAccountItemToJSON(value?: UserAccountItem | null): any {
    return UserAccountItemToJSONTyped(value, false);
}

export function UserAccountItemToJSONTyped(value?: UserAccountItem | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

