/* tslint:disable */
/* eslint-disable */
/**
 * Sportliner-lk-endpoint-api
 * Sportliner LK Endpoint API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';


/**
 * Details about system versions
 * @export
 * @interface Versions
 */
export interface Versions {
    /**
     * Application version
     * @type {string}
     * @memberof Versions
     */
    version?: string;
}

export function VersionsFromJSON(json: any): Versions {
    return VersionsFromJSONTyped(json, false);
}

export function VersionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Versions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function VersionsToJSON(value?: Versions | null): any {
    return VersionsToJSONTyped(value, false);
}

export function VersionsToJSONTyped(value?: Versions | null, ignoreDiscriminator: boolean = false): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
    };
}

